import js from '@eslint/js';
import globals from 'globals';
import importPlugin from 'eslint-plugin-import';
import chaiFriendly from 'eslint-plugin-chai-friendly';
import json from '@eslint/json';

export default [
  {
    ignores: ['build/**', 'release/**', '.yarn/**'],
  },
  { files: ['**/*.js'], ...js.configs.recommended },
  { files: ['**/*.js'], ...importPlugin.flatConfigs.errors },
  {
    files: ['**/*.js'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        ...globals.browser,
        ...globals.mocha,
        VERSION: 'readonly',
        chrome: 'readonly',
      },
    },
    plugins: {
      'chai-friendly': chaiFriendly,
    },
    rules: {
      camelcase: ['error', { properties: 'never' }],
      'no-plusplus': ['error', { allowForLoopAfterthoughts: true }],
      'one-var': ['error', 'never'],
      'prefer-template': 'error',
      'consistent-return': 'error',
      'no-lonely-if': 'error',
      'no-else-return': 'error',
      eqeqeq: 'error',
      radix: 'error',
      'no-var': 'error',
      curly: 'error',
      'dot-notation': 'error',
      'prefer-const': 'error',
      'no-console': 'error',
      'prefer-arrow-callback': 'error',
      'no-alert': 'error',
      'no-eval': 'error',
      'no-unsafe-finally': 'error',
      'no-param-reassign': 'error',
      'guard-for-in': 'error',
      'no-caller': 'error',
      'no-shadow': 'error',
      'no-bitwise': 'error',
      'no-self-compare': 'error',
      'no-nested-ternary': 'error',
      'no-octal-escape': 'error',
      'unicode-bom': 'error',
      'no-throw-literal': 'error',
      'no-iterator': 'error',
      'no-global-assign': 'error',
      'no-script-url': 'error',
      'no-return-assign': 'error',
      yoda: 'error',
      'no-loop-func': 'error',
      'no-sequences': 'error',
      'no-new-func': 'error',
      'no-implied-eval': 'error',
      'no-invalid-this': 'error',
      'no-labels': 'error',
      'no-proto': 'error',
      'no-void': 'error',
      'no-with': 'error',
      'new-cap': 'error',
      'no-ternary': 'error',
      'accessor-pairs': 'error',
      'no-div-regex': 'error',
      'array-callback-return': 'error',
      'prefer-spread': 'error',
      'prefer-rest-params': 'error',
      'no-eq-null': 'error',
      'no-restricted-syntax': ['error', 'SwitchStatement'],
      'no-extra-bind': 'error',
      'object-shorthand': 'error',
      'no-multi-str': 'error',
      'no-extend-native': 'error',
      'no-useless-call': 'error',
      'no-useless-escape': 'error',
      'no-undef-init': 'error',
      'no-undefined': 'error',
      'no-continue': 'error',
      'no-object-constructor': 'error',
      'consistent-this': 'error',
      'no-new-wrappers': 'error',
      'no-unmodified-loop-condition': 'error',
      'no-negated-condition': 'error',
      'no-implicit-coercion': 'error',
      'no-lone-blocks': 'error',
      'operator-assignment': 'error',
      'no-useless-computed-key': 'error',
      'no-useless-constructor': 'error',
      'no-useless-rename': 'error',
      'no-shadow-restricted-names': 'error',
      'no-array-constructor': 'error',
      'no-duplicate-imports': 'error',
      'require-yield': 'error',
      'prefer-destructuring': 'error',
      'no-useless-return': 'error',
      'prefer-object-spread': 'error',
      'prefer-numeric-literals': 'error',
      'func-name-matching': 'error',
      'no-return-await': 'error',
      'no-await-in-loop': 'error',
      'no-warning-comments': [
        'error',
        { terms: ['WAITING'], location: 'start' },
      ],

      // eslint:recommended enables these; the project intentionally overrides them off
      'no-prototype-builtins': 'off',
      'no-unused-expressions': 'off',
      'chai-friendly/no-unused-expressions': 'error',
    },
  },
  {
    files: ['gulpfile.babel.js', 'test/**/*.js', '**/test/**/*.js'],
    languageOptions: {
      globals: globals.node,
    },
  },
  {
    files: ['**/*.json', '.htmlhintrc', '.stylelintrc'],
    language: 'json/json',
    ...json.configs.recommended,
  },
];
